name: FusionX GCC (Eva GCC)
on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'FusionX Kernel KSUN+SUSFS'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/DjSenseii1/fusionX_sm8250'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        required: true
        default: 'main-rework'
      CODENAME:
        description: 'Phone Codename'
        default: 'MUNCH'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/DjSenseii1/AnyKernel3'
        required: false
      ANYKERNEL_BRANCH:
        description: 'AnyKernel Branch (defaults to codename)'
        default: 'amdaosp'
        required: false
      UPLOAD_TO_RELEASE:
        description: 'Upload to release'
        type: boolean
        default: false

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Custom Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "AnyKernel Url: ${{ github.event.inputs.ANYKERNEL_URL }}/tree/${{ github.event.inputs.ANYKERNEL_BRANCH }}"
        echo "::endgroup::"

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT
      id: workspace

    - name: Prepare the build environment
      run: |
        sudo apt update
        sudo apt install -y flex libncurses6 build-essential libgmp3-dev libmpc-dev libmpfr-dev
        # Download Eva GCC toolchain
        wget https://github.com/mvaisakh/gcc-arm64/archive/refs/heads/master.zip -O eva_gcc.zip
        unzip eva_gcc.zip -d eva_gcc
        # Add Eva GCC to PATH
        echo "PATH=$(pwd)/eva_gcc/gcc-arm64-master/bin:$PATH" >> $GITHUB_ENV
        echo "tools-folder=$(pwd)/eva_gcc/gcc-arm64-master/bin" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      id: tools

    - name: Verify Eva GCC Toolchain
      run: |
        aarch64-linux-gnu-gcc --version
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Clone kernel source
      run: |
        git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree
        echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      id: kernel

    - name: Building kernel
      run: |
        git submodule init && git submodule update
        bash nextpatch.sh
        export ARCH=arm64
        export SUBARCH=ARM64
        export KBUILD_BUILD_USER="SenseiiX"
        export KBUILD_BUILD_HOST="Github"
        make O=out vendor/munch_defconfig PATH="${{ steps.tools.outputs.tools-folder }}:$PATH"
        make O=out -j$(nproc --all) PATH="${{ steps.tools.outputs.tools-folder }}:$PATH" CROSS_COMPILE=aarch64-linux-gnu-
        echo "elapsed_time=$(echo "$(date +%s)"-"${{ steps.workspace.outputs.start_time }}" | bc)" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.kernel.outputs.kernel-folder }}
      id: build

    # Rest of the steps remain unchanged...
