name: Dispatcher Workflow

on:
  workflow_dispatch:
    inputs:
      UPLOAD_TO_RELEASE:
        description: 'Upload to release for all workflows'
        type: boolean
        default: false
      BUILD_TITLE_MUNCH:
        description: 'FusionX-Final-Release'
        required: false
     

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: FusionX-Final-Release
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'fx-release-stable-full.yml',
                ref: 'base',
                inputs: {
                  BUILD_TITLE: '${{ github.event.inputs. BUILD_TITLE_MUNCH }}',
                  UPLOAD_TO_RELEASE: ${{ github.event.inputs.UPLOAD_TO_RELEASE }},
                },
              });
              console.log('Successfully triggered FusionX-Final-Release');
            } catch (error) {
              console.error('Error triggering FusionX-Final-Release:', error);
              throw error;
            }
